name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Minikube, conntrack, and crictl
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo install minikube /usr/local/bin/
          sudo apt-get update
          sudo apt-get install -y conntrack
          sudo curl -s https://raw.githubusercontent.com/kubernetes-sigs/cri-tools/master/install | sudo bash

      - name: Start Minikube
        run: |
          minikube start --vm-driver=none

      - name: Get Kubeconfig
        run: |
          kubectl config view --raw > kubeconfig

      - name: Upload Kubeconfig as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: kubeconfig
          path: kubeconfig

      - name: Download Kubeconfig Artifact
        uses: actions/download-artifact@v3
        with:
          name: kubeconfig
          path: kubeconfig

      - name: Store Kubeconfig as Secret
        run: |
          echo "KUBECONFIG<<EOF
          cat kubeconfig
          echo "EOF" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/hello-python:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/hello-python:latest

      - name: Set Kubeconfig
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          context: ${{ secrets.KUBECONTEXT }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
